modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/jaredlll08/Clumps/issues"
license="MIT"
[[mods]] #mandatory
modId="clumps"
version="${file.jarVersion}"
displayName="Clumps"
displayURL="https://www.curseforge.com/minecraft/mc-mods/clumps"
updateJSONURL="https://updates.blamejared.com/get?n=clumps&gv=1.18.2"
credits=""
authors="Jaredlll08"
description='''
Clumps xp orbs together.
'''
  [[dependencies.clumps]]
	modId="forge"
	mandatory=true
	versionRange="[40.0.0,)"
	ordering="NONE"
	side="BOTH"
  [[dependencies.clumps]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"