modLoader = "javafml"
loaderVersion = "${NEO_FORGE_LOADER}"
issueTrackerURL = "${GIT_REPO}/issues"
license = "MIT"
[[mods]]
modId = "${MODID}"
updateJSONURL = "https://updates.blamejared.com/get?n=${MODID}&gv=${MINECRAFT}&ml=neoforge"
version = "${version}"
displayName = "${NAME}"
displayURL = "${CURSE_HOMEPAGE}"
authors = "${AUTHOR}"
logoFile = "icon.png"
description = '''${DESCRIPTION}'''
itemIcon = "${ITEM_ICON}"
[[mixins]]
config = "${MODID}.mixins.json"
[[dependencies.${MODID}]]
modId = "neoforge"
type = "required"
versionRange = "${NEO_FORGE_LOADER}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${MODID}]]
modId = "minecraft"
type = "required"
versionRange = "[${MINECRAFT}]"
ordering = "NONE"
side = "BOTH"